name: Router Chowder
highlights: true

### site serving configuration ###
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments
exclude :
  - CNAME
  - README.md
  - .gitignore
  - node_modules
  - _assets
  - _components

###Kramdown options
kramdown:
  input: GFM

### Add archive functionality
gems: 
  - jekyll-archives
  
### Defaults for tags
jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layouts:
    year: archive-year
    month: archive-month
    tag: archive
    category: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'