name: Chowder
markdown: redcarpet
highlights: true


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### Add Bourbon
gems: 
    - bourbon
    - neat
    - jekyll-archives

### Fix Sass Directory
sass:
    sass_dir: _sass
    style: compressed
    
### Defaults for tags

jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layouts:
    year: archive-year
    month: archive-month
    tag: archive
    category: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'