name: Router Chowder
highlights: true

### site serving configuration ###
permalink: / ## disables post output
timezone: America/Denver
lsi: false
markdown: kramdown
highlighter: rouge
exclude :
  - CNAME
  - README.md
  - .gitignore
  - node_modules
  - _assets
  - _components
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - npm-debug.log
  - bower.json
  - package.json
  

###Kramdown options
kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: true

### Add archive functionality
gems: 
  - jekyll-archives
  
### Defaults for tags
jekyll-archives:
  enabled:
    - year
    - month
    - tags
    - categories
  layouts:
    year: archive-year
    month: archive-month
    tag: archive
    category: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'